import React from 'react';

import './Ham.css';
import sackler from './Sackler.jpg';

function Sackler () {
  return (
    <div className="hamtextandimg">
        <div>
          <img className="hamfront" src={sackler} />
        </div>
        <div className="hamrightimg">
          <h1 className="hamfirsttitle">Arthur M. Sackler Museum</h1>
          <p>The Arthur M. Sackler Museum opened in 1985. The museum building, which was designed by British architect James Stirling,
            was named for the major donor, Arthur M. Sackler, a psychiatrist, entrepreneur, and philanthropist. The museum also housed
            offices for the History of Art and Architecture faculty, as well as the Digital Images and Slides Collection of the Fine Arts Library.
            As of 2016, the old Sackler Museum building houses the History of Art and Architecture Department and the Media Slide Library.
          </p>
          <h3 className="hamhistory">Collection</h3>
          <p>The museum collection holds important collections of Asian art, most notably, archaic Chinese jades (the widest collection outside of China)
            and Japanese surimono, as well as outstanding Chinese bronzes, ceremonial weapons, Buddhist cave-temple sculptures, ceramics from China and
            Korea, Japanese works on paper, and lacquer boxes, and ancient Iranian metalwork.
            The ancient Mediterranean and Byzantine collections comprise significant works in all media from Greece, Rome, Egypt, and the Near East. Strengths
            include Greek vases, small bronzes, and coins from throughout the ancient Mediterranean world.
            The museum also holds works on paper from Islamic lands and India, including paintings, drawings, calligraphy, and manuscript illustrations, with
            particular strength in Rajput art, as well as important Islamic ceramics from the 8th through to the 19th century.
          </p>
          <h3 className="hamcollection">Architecture</h3>
          <p>
          The Sackler Museum, originally designed as an extension to the Fogg, elicited worldwide attention from the time of Harvards commission of Stirling
          to design the building, following a selection process that evaluated more than 70 architects. As a measure of the excitement generated by
          the project, the University mounted an exhibition of the architects preliminary design drawings in 1981, James Stirlings Design to Expand the
          Fogg Museum and issued a portfolio of Stirlings drawings to the press.

          After completion, the buildings coverage was even greater, with general acknowledgment of the buildings significance as a Stirling design and a Harvard
          undertaking. Aside from descriptions of the buildings organization and exterior appearance, perhaps most noted was the way in which the inventive design
          accommodated its diverse program on a challenging site. Harvard published a 50-page book on the Sackler, with extensive color photos by Timothy Hursley,
          an interview with Stirling by Michael Dennis, a tribute to Arthur M. Sackler, and essays by Slive, Coolidge and Rosenfield.

          In spite of global critical acclaim, a few have been critical, Martin Peretz even proposing demolition, though his case was undermined by mis-attributing
          the building to another British architect, Norman Foster.

          As of 2013, the future use of the building was unclear, as its collection has been relocated to the Renzo Piano extension to the Fogg. Stirlings structure
          still stands as of December 2016. Since 1984, the building has housed the Universitys department of the History of Art + Architecture, with building
          renovations being completed in early 2019 to better accommodate the faculty and students.
          </p>
        </div>
      </div>
  );
}
export default Sackler;
